# Generated by Django 4.1.2 on 2022-10-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0004_course_feature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='used_techs',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
