# Generated by Django 4.1.2 on 2022-11-05 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studententrollment',
            name='order_payment_id',
        ),
    ]
