# Generated by Django 4.1.2 on 2022-11-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_studententrollment_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studententrollment',
            name='order_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
