# Generated by Django 4.1.2 on 2022-11-12 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_studententrollment_order_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studententrollment',
            old_name='entrolled_time',
            new_name='order_date',
        ),
    ]
