# Generated by Django 4.1.2 on 2022-11-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_entrolled_time_studententrollment_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studententrollment',
            name='order_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
