# Generated by Django 4.1.2 on 2022-11-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_studententrollment_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studententrollment',
            name='is_complited',
            field=models.BooleanField(default=False),
        ),
    ]
