# Generated by Django 4.1.2 on 2022-11-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_studententrollment_is_complited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studententrollment',
            old_name='is_complited',
            new_name='is_completed',
        ),
    ]
