# Generated by Django 4.1.2 on 2022-11-04 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0009_alter_chapter_course'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='courses_created',
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StudentEntrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_amount', models.CharField(blank=True, max_length=25)),
                ('order_payment_id', models.CharField(blank=True, max_length=100)),
                ('entrolled_time', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrolled_courses', to='teacher_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrolled_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
