# Generated by Django 4.1.2 on 2022-11-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_account_courses_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studententrollment',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
