# Generated by Django 4.1.2 on 2022-11-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_studententrollment_ispaid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentEntrollment',
        ),
    ]
