# Generated by Django 4.1.2 on 2022-11-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_favoritecourse_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='file',
            field=models.FileField(null=True, upload_to='assigment/'),
        ),
    ]
