# Generated by Django 4.1.2 on 2022-11-18 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0009_alter_chapter_course'),
        ('main', '0013_alter_studentassignment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_app.course'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='file',
            field=models.FileField(blank=True, upload_to='assigment/'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
