# Generated by Django 4.1.2 on 2022-11-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_account_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserating',
            name='demo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
