# Generated by Django 4.1.2 on 2022-11-18 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_courserating_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(null=True)),
                ('file', models.FileField(blank=True, upload_to='assigmentanswer/')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentassignment')),
            ],
        ),
    ]
