# Generated by Django 4.1.2 on 2022-11-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_assignmentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
